/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemvetenskapligaprojektet;
import oru.inf.InfDB; //importeras i alla klasser som vi ska använda
import oru.inf.InfException; //importeras i alla klasser som vi ska använda
import java.util.*;
import javax.swing.JTable;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.*;
import javax.swing.table.TableColumn;
/**
 *
 * @author limme
 */
public class AllaAvdelningarTest extends javax.swing.JFrame {
    private static InfDB idb;
    private String inloggadAnvandare;
    /**
     * Creates new form AllaPartners
     */
    public AllaAvdelningarTest(InfDB idb, String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        tblAvdelningar.setAutoResizeMode(tblAvdelningar.AUTO_RESIZE_OFF);
        TableColumn col = tblAvdelningar.getColumnModel().getColumn(0);
        col.setPreferredWidth(200);
        col = tblAvdelningar.getColumnModel().getColumn(1);
        col.setPreferredWidth(200);
        col = tblAvdelningar.getColumnModel().getColumn(2);
        col.setPreferredWidth(600);
        col = tblAvdelningar.getColumnModel().getColumn(3);
        col.setPreferredWidth(200);
        col = tblAvdelningar.getColumnModel().getColumn(4);
        col.setPreferredWidth(200);
        col = tblAvdelningar.getColumnModel().getColumn(5);
        col.setPreferredWidth(200);
        col = tblAvdelningar.getColumnModel().getColumn(6);
        col.setPreferredWidth(200);
        fyllTabell();
    }
    
    public void fyllTabell(){
        try{
        String[] kolumnNamn = {"avdid", "namn", "beskrivning", "adress", "epost", "telefon", "stad", "chef"};
        DefaultTableModel allaAvdelningar = new DefaultTableModel(kolumnNamn, 0);
        
        String selectAvdid = "select avdid from avdelning order by(avdid);";
        ArrayList<String> avdid = idb.fetchColumn(selectAvdid);
            if(avdid != null){
                for(String ettID:avdid){
                    String selectInfo = "select * from avdelning where avdid = " + ettID + ";";
                    HashMap<String,String> info = idb.fetchRow(selectInfo);
            
                    Object[] enRad = new Object[kolumnNamn.length];
                    int index = 0;
            
                    for(String enKolumn:kolumnNamn){
                        enRad[index++] = info.get(enKolumn);
                    }
                    allaAvdelningar.addRow(enRad);
                }
                tblAvdelningar.setModel(allaAvdelningar);
            }
        }
        catch(InfException ex){
            System.out.println(ex);
        }       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        scrAvdelningar = new javax.swing.JScrollPane();
        tblAvdelningar = new javax.swing.JTable();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Alla Avdelningar");

        tblAvdelningar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        tblAvdelningar.setPreferredSize(new java.awt.Dimension(3000, 250));
        scrAvdelningar.setViewportView(tblAvdelningar);
        if (tblAvdelningar.getColumnModel().getColumnCount() > 0) {
            tblAvdelningar.getColumnModel().getColumn(0).setMinWidth(100);
            tblAvdelningar.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblAvdelningar.getColumnModel().getColumn(0).setMaxWidth(100);
            tblAvdelningar.getColumnModel().getColumn(1).setMinWidth(500);
            tblAvdelningar.getColumnModel().getColumn(1).setPreferredWidth(500);
            tblAvdelningar.getColumnModel().getColumn(1).setMaxWidth(500);
            tblAvdelningar.getColumnModel().getColumn(2).setMinWidth(600);
            tblAvdelningar.getColumnModel().getColumn(2).setPreferredWidth(600);
            tblAvdelningar.getColumnModel().getColumn(2).setMaxWidth(600);
            tblAvdelningar.getColumnModel().getColumn(3).setMinWidth(300);
            tblAvdelningar.getColumnModel().getColumn(3).setPreferredWidth(300);
            tblAvdelningar.getColumnModel().getColumn(3).setMaxWidth(300);
            tblAvdelningar.getColumnModel().getColumn(4).setMinWidth(200);
            tblAvdelningar.getColumnModel().getColumn(4).setPreferredWidth(200);
            tblAvdelningar.getColumnModel().getColumn(4).setMaxWidth(200);
            tblAvdelningar.getColumnModel().getColumn(5).setMinWidth(200);
            tblAvdelningar.getColumnModel().getColumn(5).setPreferredWidth(200);
            tblAvdelningar.getColumnModel().getColumn(5).setMaxWidth(200);
            tblAvdelningar.getColumnModel().getColumn(6).setMinWidth(100);
            tblAvdelningar.getColumnModel().getColumn(6).setPreferredWidth(100);
            tblAvdelningar.getColumnModel().getColumn(6).setMaxWidth(100);
            tblAvdelningar.getColumnModel().getColumn(7).setMinWidth(100);
            tblAvdelningar.getColumnModel().getColumn(7).setPreferredWidth(100);
            tblAvdelningar.getColumnModel().getColumn(7).setMaxWidth(100);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrAvdelningar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 1825, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(scrAvdelningar, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllaAvdelningarTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllaAvdelningarTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllaAvdelningarTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllaAvdelningarTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AllaAvdelningarTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane scrAvdelningar;
    private javax.swing.JTable tblAvdelningar;
    // End of variables declaration//GEN-END:variables
}
