/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemvetenskapligaprojektet;
import oru.inf.InfDB; //importeras i alla klasser som vi ska använda
import oru.inf.InfException; //importeras i alla klasser som vi ska använda
import java.lang.NumberFormatException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.text.ParseException;
import java.util.Random;
/**
/**
 *
 * @author lisas
 */
public class LaggTillAnstalld extends javax.swing.JFrame {
    
    private InfDB idb;
    private String inloggadAnvandare;

    /**
     * Creates new form LaggTillAnstalld
     */
    public LaggTillAnstalld(InfDB idb, String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        lblFelID.setVisible(false); //Felmeddelanden som inte syns till en början
        lblFelEpost.setVisible(false); 
        lblFelAnstDatum.setVisible(false); 
        lblFelAvdelning.setVisible(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfID = new javax.swing.JTextField();
        btnTillbaka = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblAllaAnstallda = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblNamn = new javax.swing.JLabel();
        lblAvdelning = new javax.swing.JLabel();
        lblAnstallningsDatum = new javax.swing.JLabel();
        lblAdress = new javax.swing.JLabel();
        lblTelefonnummer = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        lblLosenord = new javax.swing.JLabel();
        tfAnstallningsFornamn = new javax.swing.JTextField();
        tfAnstallningsLosenord = new javax.swing.JTextField();
        tfAnstallningsEpost = new javax.swing.JTextField();
        tfAnstallningsTelefonnummer = new javax.swing.JTextField();
        tfAnstallningsAdress = new javax.swing.JTextField();
        tfAnstallningsDatum = new javax.swing.JTextField();
        tfAnstallningsAvdelning = new javax.swing.JTextField();
        tfAnstallningsID = new javax.swing.JTextField();
        btnTillbaka1 = new javax.swing.JButton();
        btnLaggTill = new javax.swing.JButton();
        btnSlumpaLosenord = new javax.swing.JButton();
        lblNamn1 = new javax.swing.JLabel();
        tfAnstallningsEfternamn = new javax.swing.JTextField();
        lblFelID = new javax.swing.JLabel();
        lblFelEpost = new javax.swing.JLabel();
        lblFelAnstDatum = new javax.swing.JLabel();
        lblFelAvdelning = new javax.swing.JLabel();

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAllaAnstallda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAllaAnstallda.setText("Lägg till en anställd");

        lblID.setText("ID");

        lblNamn.setText("Förnamn");

        lblAvdelning.setText("Avdelning");

        lblAnstallningsDatum.setText("Anst. datum");

        lblAdress.setText("Adress");

        lblTelefonnummer.setText("Tel.nr");

        lblEpost.setText("Epost");

        lblLosenord.setText("Lösenord");

        btnTillbaka1.setText("Tillbaka");
        btnTillbaka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbaka1ActionPerformed(evt);
            }
        });

        btnLaggTill.setText("Spara");
        btnLaggTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillActionPerformed(evt);
            }
        });

        btnSlumpaLosenord.setText("Slumpa Lösenord");
        btnSlumpaLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlumpaLosenordActionPerformed(evt);
            }
        });

        lblNamn1.setText("Efternamn");

        lblFelID.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblFelID.setForeground(new java.awt.Color(255, 0, 0));
        lblFelID.setText("ID:t existerar redan");

        lblFelEpost.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblFelEpost.setForeground(new java.awt.Color(255, 0, 0));
        lblFelEpost.setText("Vänligen fyll i en giltig epostadress");

        lblFelAnstDatum.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblFelAnstDatum.setForeground(new java.awt.Color(255, 0, 0));
        lblFelAnstDatum.setText("Vänligen använd ett korrekt datumformat");

        lblFelAvdelning.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblFelAvdelning.setForeground(new java.awt.Color(255, 0, 0));
        lblFelAvdelning.setText("Avdelningen finns ej");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSlumpaLosenord)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTelefonnummer)
                                    .addComponent(lblEpost)
                                    .addComponent(lblLosenord)
                                    .addComponent(lblAnstallningsDatum)
                                    .addComponent(lblAdress)
                                    .addComponent(lblNamn1)
                                    .addComponent(lblNamn)
                                    .addComponent(lblID)
                                    .addComponent(lblAvdelning))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFelID)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(42, 42, 42)
                                            .addComponent(btnLaggTill)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                                            .addComponent(btnTillbaka1))
                                        .addComponent(tfAnstallningsEfternamn, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfAnstallningsAdress, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfAnstallningsEpost, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfAnstallningsTelefonnummer, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfAnstallningsDatum, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfAnstallningsAvdelning)
                                        .addComponent(tfAnstallningsFornamn, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfAnstallningsID, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfAnstallningsLosenord, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(lblFelEpost)
                                    .addComponent(lblFelAnstDatum)
                                    .addComponent(lblFelAvdelning))))
                        .addContainerGap(48, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAllaAnstallda)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblAllaAnstallda)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(tfAnstallningsID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblFelID)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamn)
                    .addComponent(tfAnstallningsFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamn1)
                    .addComponent(tfAnstallningsEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdress)
                    .addComponent(tfAnstallningsAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEpost)
                    .addComponent(tfAnstallningsEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblFelEpost)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonnummer)
                    .addComponent(tfAnstallningsTelefonnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnstallningsDatum)
                    .addComponent(tfAnstallningsDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblFelAnstDatum)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLosenord)
                    .addComponent(tfAnstallningsLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdelning)
                    .addComponent(tfAnstallningsAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblFelAvdelning)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSlumpaLosenord)
                    .addComponent(btnLaggTill)
                    .addComponent(btnTillbaka1))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        new AllaAnstallda(idb,inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnTillbaka1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbaka1ActionPerformed
// RÅKA LÄGGA TILL TVÅ GGR OCH KAN INTE TA BORT OBS
        new AllaAnstallda(idb,inloggadAnvandare).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTillbaka1ActionPerformed

    private void btnLaggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillActionPerformed
        try{
           String textAID = tfAnstallningsID.getText(); 
           String fornamn = tfAnstallningsFornamn.getText();
           String efternamn = tfAnstallningsEfternamn.getText();
           String adress = tfAnstallningsAdress.getText();
           String epost = tfAnstallningsEpost.getText();
           String telefon = tfAnstallningsTelefonnummer.getText();
           String anstallningsDatum = tfAnstallningsDatum.getText();
           String losenord = tfAnstallningsLosenord.getText();
           String avdelningsID = tfAnstallningsAvdelning.getText(); 
           
           int aid = Integer.parseInt(textAID); //Gör om från String till int
           int avdelning = Integer.parseInt(avdelningsID); //Gör om från String till int
           
           
           //Kollar ifall aid redan finns i databasen
           String checkaID = "select aid from anstalld where aid = " + aid + ";";
           String idFinns = idb.fetchSingle(checkaID);
           
           //Kollar ifall avdelning redan finns i databasen
           String checkaAvdid = "select avdelning from anstalld where avdelning = " + avdelning + ";";
           String avdidFinns = idb.fetchSingle(checkaAvdid);
           
           
           //Ifall idFinns finns i databasen så visas felmeddelandet
           if(idFinns != null){ 
               lblFelID.setVisible(true);
           }
           
           //Ifall avdidFinns inte finns i databasen så visas felmeddelandet
           if(avdidFinns == null) {
               lblFelAvdelning.setVisible(true);
           }
           
           SimpleDateFormat inputFormat = new SimpleDateFormat("yyyy-MM-dd"); // Konvertera anställningsdatum till rätt format
           inputFormat.setLenient(false); // Gör parsning strikt
           Date datumString = inputFormat.parse(anstallningsDatum); // Konvertera strängen till ett Date-objekt
           
           String datum = inputFormat.format(datumString); // Om allt är OK, formatera datumet och sätt in i databasen
           
           String insertNyAnstalld = "insert into anstalld (aid, fornamn, efternamn, adress, epost, telefon, anstallningsdatum, losenord, avdelning) values (" + aid + ", '" + fornamn + "', '" + efternamn + "', '" + adress + "', '" + epost + "', '" + telefon + "', '" + datum + "', '" + losenord + "', " + avdelning +");";
           idb.insert(insertNyAnstalld);
           
           new AllaAnstallda(idb,inloggadAnvandare).setVisible(true);
           this.setVisible(false);
           }
        catch(ParseException ex) {
            lblFelAnstDatum.setVisible(true); // Visa felmeddelandet om datumformatet är felaktigt
        }
        
        catch(NumberFormatException ex) {
            lblFelID.setVisible(true); // Om aid inte är ett heltal
            lblFelAvdelning.setVisible(true); // Om avdid inte är ett heltal
        }
        
        catch(InfException ex){ //Catch InfExceptions?
            System.out.println(ex);
            }
        
    }//GEN-LAST:event_btnLaggTillActionPerformed

    private void btnSlumpaLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlumpaLosenordActionPerformed
        int langdLosenord = 11; //Längden på lösenordet blir 11
        
        //De tecken som kan ingå i lösenordet
        String allaTecken = "QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm1234567890";
        StringBuilder slumpatLosenord = new StringBuilder();
        
        //Slumpgenerator
        java.util.Random random = new java.util.Random();
        
        //Generera slumpmässigt lösenord
        for(int i = 0; i < langdLosenord; i++) {
            int x = random.nextInt(allaTecken.length());
            slumpatLosenord.append(allaTecken.charAt(x));
        }
        
        tfAnstallningsLosenord.setText(slumpatLosenord.toString());
    }//GEN-LAST:event_btnSlumpaLosenordActionPerformed

    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaggTillAnstalld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaggTillAnstalld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaggTillAnstalld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaggTillAnstalld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new LaggTillAnstalld().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaggTill;
    private javax.swing.JButton btnSlumpaLosenord;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JButton btnTillbaka1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblAllaAnstallda;
    private javax.swing.JLabel lblAnstallningsDatum;
    private javax.swing.JLabel lblAvdelning;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblFelAnstDatum;
    private javax.swing.JLabel lblFelAvdelning;
    private javax.swing.JLabel lblFelEpost;
    private javax.swing.JLabel lblFelID;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblNamn1;
    private javax.swing.JLabel lblTelefonnummer;
    private javax.swing.JTextField tfAnstallningsAdress;
    private javax.swing.JTextField tfAnstallningsAvdelning;
    private javax.swing.JTextField tfAnstallningsDatum;
    private javax.swing.JTextField tfAnstallningsEfternamn;
    private javax.swing.JTextField tfAnstallningsEpost;
    private javax.swing.JTextField tfAnstallningsFornamn;
    private javax.swing.JTextField tfAnstallningsID;
    private javax.swing.JTextField tfAnstallningsLosenord;
    private javax.swing.JTextField tfAnstallningsTelefonnummer;
    private javax.swing.JTextField tfID;
    // End of variables declaration//GEN-END:variables
}
