/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemvetenskapligaprojektet;
import oru.inf.InfDB; //importeras i alla klasser som vi ska använda
import oru.inf.InfException; //importeras i alla klasser som vi ska använda
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author meam
 */
public class MinaSidor extends javax.swing.JFrame {

    private InfDB idb;
    private String inloggadAnvandare;
    private String text;
    
    /**
     * Creates new form MinaSidor
     */
    public MinaSidor(InfDB idb,String inloggadAnvandare) {
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        
        initComponents();
        taFramInfo();
        taFramArbetsroll();
    }

     private void taFramInfo(){
        try{
        String selectAid = "select aid from anstalld where epost = '" + inloggadAnvandare + "';";
        String anstalldsId = idb.fetchSingle(selectAid);
        tfAid.setText(anstalldsId);
        
        String selectFornamn = "select fornamn from anstalld where epost = '" + inloggadAnvandare + "';";
        String anstalldsFornamn = idb.fetchSingle(selectFornamn);
        tfFornamn.setText(anstalldsFornamn);
        
        String selectEfternamn = "select efternamn from anstalld where epost = '" + inloggadAnvandare + "';";
        String anstalldsEfternamn = idb.fetchSingle(selectEfternamn);
        tfEfternamn.setText(anstalldsEfternamn);
        
        String selectTelefonnummer = "select telefon from anstalld where epost = '" + inloggadAnvandare + "';";
        String anstalldsTelefon = idb.fetchSingle(selectTelefonnummer);
        tfTelefonnummer.setText(anstalldsTelefon);
        
        String selectEpost = "select epost from anstalld where epost = '" + inloggadAnvandare + "';";
        String anstalldsEpost = idb.fetchSingle(selectEpost);
        tfEpost.setText(anstalldsEpost);
        
        String selectAdress = "select adress from anstalld where epost = '" + inloggadAnvandare + "';";
        String anstalldsAdress = idb.fetchSingle(selectAdress);
        tfAdress.setText(anstalldsAdress);
        
        String selectAvdelning = "select avdelning from anstalld where epost = '" + inloggadAnvandare + "';";
        String anstalldsAvdelning = idb.fetchSingle(selectAvdelning); //Ok även om avdelningsnummret egentligen är en int?.
        tfAvdelning.setText(anstalldsAvdelning);
        
        String selectAnstallningsdatum ="select anstallningsdatum from anstalld where epost = '" + inloggadAnvandare + "';";
        String anstalldsAnstallningsdatum = idb.fetchSingle(selectAnstallningsdatum);
        tfAnstallningsdatum.setText(anstalldsAnstallningsdatum);
        
    }
        catch(InfException ex){
            System.out.println(ex); //Ska det stå ex.getMessage()??
            
        }
    }
    
    private void taFramArbetsroll(){
        ArrayList<String> projektchef = new ArrayList<>();
        ArrayList<String> handlaggare = new ArrayList<>();
        text = "Administratör";
        try{
             String selectAid = "select aid from anstalld where epost = '" + inloggadAnvandare + "';";
            String anstalldsId = idb.fetchSingle(selectAid); 
            
            String selectProjektchef = "select projektchef from projekt;";
            projektchef = idb.fetchColumn(selectProjektchef);
            
            String selectHandlaggare = "select aid from handlaggare;";
            handlaggare = idb.fetchColumn(selectHandlaggare);
          
            for(String ettProjektchefsId : projektchef){
                if(ettProjektchefsId.equals(anstalldsId)){
                    text = "Handläggare/Projektchef";
                }
            }
            for(String enHandlaggare : handlaggare){
                if(enHandlaggare.equals(anstalldsId)){
                    text = "Handläggare";
                }
            }
            tfArbetsRoll.setText(text); 
            }
            
        catch (InfException ex) {
            System.out.println(ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField11 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfAid = new javax.swing.JTextField();
        tfFornamn = new javax.swing.JTextField();
        tfEfternamn = new javax.swing.JTextField();
        tfTelefonnummer = new javax.swing.JTextField();
        tfEpost = new javax.swing.JTextField();
        tfAdress = new javax.swing.JTextField();
        tfAvdelning = new javax.swing.JTextField();
        tfArbetsRoll = new javax.swing.JTextField();
        lblAid = new javax.swing.JLabel();
        lblAvdelning = new javax.swing.JLabel();
        btnSpara = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();
        btnRedigeraUppgifter = new javax.swing.JButton();
        lblAnstalldSedan = new javax.swing.JLabel();
        tfAnstallningsdatum = new javax.swing.JTextField();

        jTextField11.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Mina sidor");

        tfAid.setEditable(false);

        tfFornamn.setEditable(false);

        tfEfternamn.setEditable(false);

        tfTelefonnummer.setEditable(false);

        tfEpost.setEditable(false);

        tfAdress.setEditable(false);

        tfAvdelning.setEditable(false);

        tfArbetsRoll.setEditable(false);

        lblAid.setText("#");

        lblAvdelning.setText("Avdelning");

        btnSpara.setText("Spara");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnRedigeraUppgifter.setText("Redigera Uppgifter");
        btnRedigeraUppgifter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedigeraUppgifterActionPerformed(evt);
            }
        });

        lblAnstalldSedan.setText("Anställd sedan");

        tfAnstallningsdatum.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRedigeraUppgifter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSpara)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTillbaka))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfAdress, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfFornamn, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfEfternamn, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTelefonnummer, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfEpost, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblAid)
                                        .addGap(3, 3, 3)
                                        .addComponent(tfAid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblAnstalldSedan, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfAnstallningsdatum, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfArbetsRoll, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblAvdelning)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tfAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 33, Short.MAX_VALUE)))
                        .addGap(95, 95, 95)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfAid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAid))
                        .addGap(18, 18, 18)
                        .addComponent(tfFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfTelefonnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAvdelning)
                        .addComponent(tfAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(tfArbetsRoll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnstalldSedan)
                    .addComponent(tfAnstallningsdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSpara)
                    .addComponent(btnTillbaka)
                    .addComponent(btnRedigeraUppgifter))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        if(text.equals("Handläggare") || text.equals("Hansläggare/Projektchef")){
            new MenyHandlaggare(idb, inloggadAnvandare).setVisible(true);
        }
        else{
            new MenyAdmin(idb, inloggadAnvandare).setVisible(true);   
        }
        this.setVisible(false);           
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnRedigeraUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedigeraUppgifterActionPerformed
        tfFornamn.setEditable(true);  
        tfEfternamn.setEditable(true);
        tfAdress.setEditable(true);
    }//GEN-LAST:event_btnRedigeraUppgifterActionPerformed

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        try{
            String fornamn = tfFornamn.getText();
            String updateFornamn = "UPDATE anstalld SET fornamn ='"+ fornamn + "' WHERE epost ='"+ inloggadAnvandare + "';";
            idb.update(updateFornamn);
        
            String efternamn = tfEfternamn.getText();
            String updateEfternamn = "UPDATE anstalld SET efternamn ='"+ efternamn + "' WHERE epost ='"+ inloggadAnvandare + "';";
            idb.update(updateEfternamn);
        
            String adress = tfAdress.getText();
            String updateAdress = "UPDATE anstalld SET adress ='"+ adress + "' WHERE epost ='"+ inloggadAnvandare + "';";
            idb.update(updateAdress);
        }
        catch(InfException ex){
            System.out.println(ex);
        }
        
        enableOff();
        
    }//GEN-LAST:event_btnSparaActionPerformed

    private void enableOff(){
        tfFornamn.setEditable(false);  
        tfEfternamn.setEditable(false);
        tfAdress.setEditable(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MinaSidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MinaSidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MinaSidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MinaSidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MinaSidor().setVisible(true);
            }
        });
    }
    
    
   
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRedigeraUppgifter;
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JLabel lblAid;
    private javax.swing.JLabel lblAnstalldSedan;
    private javax.swing.JLabel lblAvdelning;
    private javax.swing.JTextField tfAdress;
    private javax.swing.JTextField tfAid;
    private javax.swing.JTextField tfAnstallningsdatum;
    private javax.swing.JTextField tfArbetsRoll;
    private javax.swing.JTextField tfAvdelning;
    private javax.swing.JTextField tfEfternamn;
    private javax.swing.JTextField tfEpost;
    private javax.swing.JTextField tfFornamn;
    private javax.swing.JTextField tfTelefonnummer;
    // End of variables declaration//GEN-END:variables
}
